version: '3'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DB_USER: your_username
      DB_PASS: your_password
      DB_NAME: your_database_name
      NODE_ENV: production
    network_mode: host

  postgres:
    restart: always
    image: postgres
    container_name: postgres-nestTemplate
    volumes:
      - postgres-nestTemplate:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    network_mode: host
volumes:
  postgres-nestTemplate:

